Repository The-Strongest-bbik/bbik, pull requests merged in 2025-06, with the labels that each got.

#4 📌 Add: SwiftLint Then SnapKit 패키지 추가
  Bbik.xcodeproj/project.pbxproj
  Bbik.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 📌 Add

#12 Add/#11 swftlintpackage 재설정 및 .swiftlint.yml 파일 생성
  .swiftlint.yml
  Bbik.xcodeproj/project.pbxproj
  Bbik.xcodeproj/project.xcworkspace/xcuserdata/yooni.xcuserdatad/UserInterfaceState.xcuserstate
  Bbik/Application/AppDelegate.swift
  Bbik/Application/SceneDelegate.swift
  Bbik/Source/ViewController/ViewController.swift
Labels: 📌 Add

#14 💡 Chore: gitinore파일수정
  .gitignore
Labels: 💡 Chore

#19 📌 Add: data.json 파일업로드
  Bbik.xcodeproj/project.xcworkspace/xcuserdata/yooni.xcuserdatad/UserInterfaceState.xcuserstate
  Bbik/Resource/endata.json
  Bbik/Resource/krdata.json
Labels: 📌 Add

#24 Add/#23 create shop model
  .github/ISSUE_TEMPLATE/add-issue-탬플릿.md
  .github/ISSUE_TEMPLATE/doc-issues-탬플릿.md
  .github/ISSUE_TEMPLATE/perf-issue-템플릿.md
  .github/ISSUE_TEMPLATE/refactor-issues-탬플릿.md
  Bbik/Resource/endata.json
  Bbik/Resource/krdata.json
  Bbik/Source/Model/ShopDataService.swift
  Bbik/Source/Model/ShopModel.swift
  Bbik/Source/View/ShopView.swift
  Bbik/Source/ViewController/ViewController.swift
Labels: 📌 Add

#27 Feat/#18 items
  Bbik/Source/Service/ImageFetcher.swift
  Bbik/Source/View/ShopCell.swift
  Bbik/Source/View/ShopView.swift
  Bbik/Source/ViewController/ViewController.swift
Labels: ✨ Feat

#30 💡 Chore: UIPageControl 색상 변경 및 메인 블루 컬러 추가
  Bbik/Resource/Assets.xcassets/MainBlue.colorset/Contents.json
  Bbik/Source/View/ShopView.swift
Labels: 💡 Chore

#33 ✨ Feat: 메뉴카테고리바
  Bbik/Source/View/ShopView.swift
  Bbik/Source/ViewController/ViewController.swift
Labels: ✨ Feat

#35 ✨ Feat/#34 bottom view
  Bbik.xcodeproj/project.pbxproj
  Bbik/Source/View/ShopView.swift
  Bbik/Source/ViewController/ViewController.swift
Labels: ✨ Feat

#37 💡 Chore: UIPageControl의 터치 제거
  Bbik/Source/View/ShopView.swift
Labels: 💡 Chore

#40 💡 Chore: 카테고리 버튼 클릭시 첫번쨰 페이지로 가기
  Bbik/Source/ViewController/ViewController.swift
Labels: 💡 Chore

#43 💡 Chore: 시스템 설정 언어에 따른 디코딩 파일 변경
  Bbik/Resource/endata.json
  Bbik/Source/Model/ShopModel.swift
  Bbik/Source/ViewController/ViewController.swift
Labels: 💡 Chore

#44 ✨ Feat: Localizable 다국어 기능 추가
  Bbik.xcodeproj/project.pbxproj
  Bbik/Application/ko.lproj/LaunchScreen.strings
  Bbik/Resource/Localizable.xcstrings
  Bbik/Source/Extensions/String++.swift
  Bbik/Source/View/ShopCell.swift
  Bbik/Source/View/ShopView.swift
Labels: ✨ Feat

#46 ✨ Feat: new, hot 이미지 에셋 추가 및 태그 기능 추가
  Bbik/Resource/Assets.xcassets/hot.imageset/Contents.json
  Bbik/Resource/Assets.xcassets/hot.imageset/hot.png
  Bbik/Resource/Assets.xcassets/new.imageset/Contents.json
  Bbik/Resource/Assets.xcassets/new.imageset/new.png
  Bbik/Source/View/ShopCell.swift
Labels: ✨ Feat

#52 🚨 Fix: 로고 변수명 수정
  Bbik/Source/View/ShopView.swift
Labels: 🚨 Fix

#56 🚨 Fix: 상품을 담으면 총금액라벨과 장바구니보기 버튼이 뭉개지는 버그
  Bbik/Source/View/ShopView.swift
  Bbik/Source/ViewController/ViewController.swift
Labels: 🚨 Fix

#57 📌 Add: 장바구니 뷰 구현
  Bbik/Application/AppDelegate.swift
  Bbik/Application/SceneDelegate.swift
  Bbik/Source/Component/QuantityControl.swift
  Bbik/Source/Extensions/Int++.swift
  Bbik/Source/Model/CartModel.swift
  Bbik/Source/Model/ShopModel.swift
  Bbik/Source/Service/CartManager.swift
  Bbik/Source/Service/ImageFetcher.swift
  Bbik/Source/Service/ShopDataService.swift
  Bbik/Source/View/CartItemCell.swift
  Bbik/Source/View/CartView.swift
  Bbik/Source/View/ShopCell.swift
  Bbik/Source/View/ShopView.swift
  Bbik/Source/ViewController/CartViewController.swift
  Bbik/Source/ViewController/ViewController.swift
Labels: 📌 Add
